name: Hadolint
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: lint mysql
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: mysql/Dockerfile
      - name: lint rabbitmq
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: rabbitmq/Dockerfile
      - name: lint jenkins
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: jenkins/Dockerfile
