name: Hadolint
on:
  push:
    paths:
      - ".github/workflows/hadolint.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0
      - name: lint mysql
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: mysql/Dockerfile
      - name: lint rabbitmq
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: rabbitmq/Dockerfile
      - name: lint jenkins
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: jenkins/Dockerfile
