name: Tag Actions

on:
  release:
    types: [created]

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
    - name: set env
      run: |
        export TAG_NAME="${{ github.event.release.tag_name }}"
        export TAG_NAME_NOTV=echo ${TAG_NAME} | cut -c 2-
        echo ::set-env name=GIT_TAG_VER::"${TAG_NAME}"
        echo ::set-env name=MVN_BLD_VER::"${TAG_NAME_NOTV}"
